### ISSUE TITLE
postMessage() problem with Safari (cont. from mkdocs-localsearch)

### ISSUE THREAD

**Issue by ronligt** [squidfunk/iframe-worker#100]
Using iframe-worker in Safari results in the following error:

<img width="612" alt="Screenshot 2020-09-23 at 10 32 59" src="https://user-images.githubusercontent.com/6848987/94015423-20d1a080-fdad-11ea-831e-f67f89fe9551.png">

This problem was previously reported in `mkdocs-localsearch`:

* <https://github.com/wilhelmer/mkdocs-localsearch/issues/10>

## Versions

iframe-worker: 0.1.7
safari: 14.0

**Comment by squidfunk** [comment]
Fixed in e71a94ccb6c101c7d5610546d10419f1f017612a and released as part of 0.1.8. The problem was that Safari doesn't set a default origin, which the polyfilled `postMessage` function will now set to '*'. I tested Chrome, Firefox and Safari and all seem to be working:

![Ohne Titel](https://user-images.githubusercontent.com/932156/94033470-4799d200-fdc1-11ea-8cea-7fd44c26d2ca.gif)

**Comment by ronligt** [comment]
Thank you very much @squidfunk! The `mkdocs-localsearch` now works fantastic :-)
